"""
Django settings for smmsproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from celery.schedules import crontab

# Load environment variables from the .env file FIRST so that every setting
# below reads the real (rotated) values. Placing this here rather than further
# down fixes a bug where SECRET_KEY and DB_PASSWORD were read before .env was
# loaded, silently falling back to committed defaults.
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# custome user model
AUTH_USER_MODEL = 'smmsapp.CustomUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


def require_env(name: str) -> str:
    """Read a required env var, failing loudly if it is missing or empty.

    Used for secrets that MUST NOT fall back to a default. A misconfigured
    deployment should refuse to start rather than silently run with a
    publicly-known key or password.
    """
    value = os.getenv(name)
    if not value:
        raise ImproperlyConfigured(
            f"Missing required environment variable: {name}"
        )
    return value


# SECURITY WARNING: keep the secret key used in production secret!
# No default: the service refuses to start unless SECRET_KEY is provided.
SECRET_KEY = require_env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Fail-safe: DEBUG defaults to False. A missing/unset DEBUG env var must NOT
# silently enable debug mode. Dev environments set DEBUG=True explicitly.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Origin lists are read from the environment so each deployment (staging vs
# prod) ships its own explicit list. Changing the lists requires no code edit.
# Values are comma-separated; an empty/unset var yields an empty list (closed by default).
CORS_ALLOWED_ORIGINS = [
    o for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o
]
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_CREDENTIALS = True  # Allow cookies, tokens, and authentication credentials

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS considerations:
#  - Nginx terminates TLS at the edge and redirects HTTP->HTTPS, so the app does
#    not force its own redirect. Keep SECURE_SSL_REDIRECT off behind that proxy;
#    enable it only when the app itself terminates TLS.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
if os.getenv('SECURE_HSTS_SECONDS', ''):
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True') == 'True'

SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'  # HTTPS only
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'  # HTTPS only

# ---- FIREBASE SETUP
FIREBASE_API_KEY = os.getenv('FIREBASE_API_KEY')
FIREBASE_SENDER_ID = os.getenv('FIREBASE_SENDER_ID')
FIREBASE_PROJECT_ID=os.getenv('FIREBASE_PROJECT_ID')

# ---- API BASE URL ----
API_BASE_URL = os.getenv('API_BASE_URL', 'http://127.0.0.1:8000')

# ---- EMAIL CONDIFURATIONS ----
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- for message engine
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')  
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BEAT_SCHEDULE = {
    "send-pending-notifications": {
        "task": "smmsapp.tasks.send_pending_notifications",
        "schedule": crontab(minute="*/5"),  # Run every 5 minutes
    },
    "check-balance-thresholds": {
        "task": "smmsapp.tasks.check_balance_thresholds",
        "schedule": crontab(hour="*/6"),  # Run every 6 hours
    },
}

# Default low-balance threshold (Tsh) used when a parent has no explicit balance_threshold.
DEFAULT_BALANCE_THRESHOLD = '1000.00'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'smmsapp',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smmsproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smmsproject.wsgi.application'

# ----- DATABASE PRODUCTION -----
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'smmsdb'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': require_env('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',             # global anonymous ceiling
        'login': '5/min',             # brute-force / credential-enumeration guard
        'forget_password': '3/min',   # account-enumeration guard
    },
}

# ---- ACCESS AND REFRESH TOKEN -----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # access token to 15 min
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # refresh token to 1 days
    "ROTATE_REFRESH_TOKENS": True,  # Issue a new refresh token on refresh
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist old refresh tokens
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'

MEDIA_URL = "/uploads/"
MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# WhiteNoise configuration for production static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
