# Generated by Django 5.0.6 on 2026-08-28 09:12

from django.db import migrations, models


def rewrite_penalt_to_penalty(apps, schema_editor):
    """Normalise the misspelled 'penalt' status to 'penalty' in existing rows."""
    Transaction = apps.get_model('smmsapp', 'Transaction')
    Transaction.objects.filter(transaction_status='penalt').update(transaction_status='penalty')


def reverse_rewrite(apps, schema_editor):
    """Reverse the rewrite: restore the misspelled value."""
    Transaction = apps.get_model('smmsapp', 'Transaction')
    Transaction.objects.filter(transaction_status='penalty').update(transaction_status='penalt')


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rewrite_penalt_to_penalty, reverse_rewrite),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('penalty', 'Penalty')], default='pending', max_length=10),
        ),
    ]
