# Generated by Django 5.0.6 on 2025-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0002_remove_rfidcard_qrcode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
