# Generated by Django 5.0.6 on 2026-08-29 07:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0003_redact_password_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-500.00'))]),
        ),
        migrations.AddConstraint(
            model_name='rfidcard',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', Decimal('-500.00'))), name='rfidcard_balance_floor_gte_minus500'),
        ),
    ]
