# Generated by Django 5.0.6 on 2025-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0003_customuser_class_room_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
