# Generated by Django 5.0.6 for the card replacement feature. Manual migration.

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0005_passwordresettoken'),
    ]

    operations = [
        # Convert RFIDCard.student_or_staff from OneToOne to ForeignKey so a
        # student/staff may own multiple cards (a deactivated old card + an
        # active replacement). This removes the DB-level UNIQUE constraint that
        # OneToOneField added. The invariant "one ACTIVE card per student/staff"
        # is enforced at the application layer (CreateCardView, ReplaceCardView,
        # scan). The field remains required (non-null).
        migrations.AlterField(
            model_name='rfidcard',
            name='student_or_staff',
            field=models.ForeignKey(
                help_text='Owner of the card. A student/staff may have multiple cards',
                limit_choices_to={'role__in': ['student', 'staff']},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='rfid_cards',
                to='smmsapp.customuser',
                verbose_name='student or staff',
            ),
        ),
        migrations.CreateModel(
            name='ReplacementLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for replacement (e.g. card lost or damaged)')),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('new_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_of', to='smmsapp.rfidcard')),
                ('old_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_by', to='smmsapp.rfidcard')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='Admin who performed the replacement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_replacements', to='smmsapp.customuser')),
            ],
        ),
    ]
