# Generated by Django 5.0.6 on 2025-02-08 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0005_alter_customuser_gender_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='parent',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('system', 'System Update'), ('reminder', 'Reminder'), ('message', 'Message')], default='message', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smmsapp.transaction'),
        ),
    ]
