# Generated by Django 5.0.6 on 2025-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0006_remove_notification_parent_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=50),
        ),
    ]
