# Generated by Django 5.0.6 for the low-balance threshold feature. Manual migration.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0006_rfidcard_fk_replacementlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance_threshold',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Per-parent default balance threshold that triggers a low-balance reminder for their children. Null falls back to the system default.',
                max_digits=10,
                null=True,
            ),
        ),
    ]
