# Generated by Django 5.0.6 on 2025-02-08 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0007_scansession_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='scansession',
            old_name='created_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='scansession',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school_name',
            field=models.ForeignKey(default=2434, on_delete=django.db.models.deletion.CASCADE, to='smmsapp.school'),
            preserve_default=False,
        ),
    ]
