# Generated by Django 5.0.6 on 2025-02-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0008_school_rename_created_at_scansession_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
