# Generated by Django 5.0.6 on 2026-09-30 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0009_sms_opt_out_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase / Penalty'), ('deposit', 'Deposit'), ('reversal', 'Reversal'), ('card_replacement', 'Card Replacement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_value', models.DecimalField(decimal_places=2, help_text='Sum of all ScannedData.item.price for this session', max_digits=10)),
                ('expected_cash', models.DecimalField(decimal_places=2, help_text='Operator-entered till/cash amount', max_digits=10)),
                ('variance', models.DecimalField(decimal_places=2, editable=False, help_text='expected_cash - scanned_value', max_digits=10)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('variance', 'Variance')], default='matched', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why there is variance (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Reason for reversal')),
                ('ref', models.CharField(blank=True, help_text='Optional reversal reference number', max_length=50)),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reversed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='smmsapp_aud_timesta_236767_idx',
            old_name='smmsapp_aud_timesta_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='smmsapp_aud_actor_i_355aec_idx',
            old_name='smmsapp_aud_actor_i_123457_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='smmsapp_aud_action_77b9de_idx',
            old_name='smmsapp_aud_action__123458_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='smmsapp_sms_recipie_28e20c_idx',
            old_name='smmsapp_sms_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='smmsapp_sms_status_cedf36_idx',
            old_name='smmsapp_sms_status__idx',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Parent who requested the deposit (optional, for audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_voided',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when a reversal restores the balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Scan session that produced this transaction (for audit & reversal)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmsapp.scansession'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='student_or_staff',
            field=models.ForeignKey(help_text='Owner of the card. A student/staff may have multiple cards', limit_choices_to={'role__in': ['student', 'staff']}, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ref_deposit',
            field=models.ForeignKey(blank=True, help_text='Bank deposit that credited the balance (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmsapp.bankdeposit'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ref_transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction reversed/deposited (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='smmsapp.transaction'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='rfid_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smmsapp.rfidcard'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smmsapp.scansession'),
        ),
        migrations.AddField(
            model_name='reversal',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='Operator/admin who voided the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reversal',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smmsapp.transaction'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['rfid_card', 'timestamp'], name='smmsapp_led_rfid_ca_7a5d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['status', 'created_at'], name='smmsapp_rec_status_9e5c05_idx'),
        ),
        migrations.AddIndex(
            model_name='reversal',
            index=models.Index(fields=['transaction', 'reversed_at'], name='smmsapp_rev_transac_537910_idx'),
        ),
    ]
