# Generated by Django 5.0.6 on 2025-02-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0011_customuser_parent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='insufficient_meal_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
