# Generated by Django 5.0.6 on 2025-02-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0012_rfidcard_insufficient_meal_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddata',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smmsapp.canteenitem'),
        ),
    ]
