# Generated by Django 5.0.6 on 2025-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0013_scanneddata_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
