# Generated by Django 5.0.6 on 2025-02-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0014_notification_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('penalt', 'Penalt')], default='pending', max_length=10),
        ),
    ]
