# Generated by Django 5.0.6 on 2026-10-08 13:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0019_journal_ledger_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=50)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('no_show', 'No show'), ('expired', 'Expired')], db_index=True, default='placed', max_length=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cutoff_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fulfilled_quantity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='smmsapp_jou_event_t_3ce439_idx',
            old_name='smmsapp_jo_event_t_d9c399_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='smmsapp_jou_rfid_ca_1fc3cd_idx',
            old_name='smmsapp_jo_rfid_ca_0e7b07_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='smmsapp_jou_account_36d079_idx',
            old_name='smmsapp_jo_account_eb35de_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='rfidcard',
            name='held_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='rfidcard',
            constraint=models.CheckConstraint(check=models.Q(('held_balance__gte', 0)), name='rfidcard_held_balance_nonnegative'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preorders', to='smmsapp.rfidcard'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_preorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preorder_items', to='smmsapp.canteenitem'),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='preorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='smmsapp.preorder'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='preorder_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='smmsapp.preorderitem'),
        ),
        migrations.AddIndex(
            model_name='preorder',
            index=models.Index(fields=['date', 'meal_type', 'status'], name='smmsapp_pre_date_49ecd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='preorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'placed')), fields=('student', 'date', 'meal_type'), name='uniq_active_preorder_student_date_meal'),
        ),
        migrations.AddConstraint(
            model_name='preorderitem',
            constraint=models.UniqueConstraint(fields=('preorder', 'item'), name='uniq_preorder_item'),
        ),
        migrations.AddConstraint(
            model_name='preorderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='preorder_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='preorderitem',
            constraint=models.CheckConstraint(check=models.Q(('fulfilled_quantity__lte', models.F('quantity'))), name='preorder_fulfilled_not_over_quantity'),
        ),
    ]
