# Generated by Django 5.0.6 on 2026-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0021_seed_preorder_feature'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('recipient', 'dedupe_key'), name='uniq_notification_recipient_dedupe'),
        ),
    ]
