# Generated by Django 5.0.6 on 2026-10-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0024_stocklevel_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='smmsapp.transaction'),
        ),
    ]
