# Generated by Django 5.0.6 on 2026-10-09 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0025_stockmovement_source_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('meals', models.PositiveIntegerField(default=0)),
                ('unique_students', models.PositiveIntegerField(default=0)),
                ('deposits_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reversals', models.PositiveIntegerField(default=0)),
                ('variance_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='txn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_status', 'is_voided'], name='txn_status_void_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystats',
            constraint=models.UniqueConstraint(fields=('date', 'meal_type'), name='uniq_daily_stats_date_meal'),
        ),
    ]
