# Generated by Django 5.0.6 on 2026-10-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0026_dailystats_transaction_txn_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightflag',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='reference_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='reference_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insightflag',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='insightflag',
            name='scan_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_flags_a', to='smmsapp.scanneddata'),
        ),
        migrations.AlterField(
            model_name='insightflag',
            name='scan_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_flags_b', to='smmsapp.scanneddata'),
        ),
        migrations.AddConstraint(
            model_name='insightflag',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__isnull', False), ('reference_type__isnull', False)), fields=('kind', 'reference_type', 'reference_id'), name='uniq_insight_reference'),
        ),
    ]
