# Generated by Django 5.0.6 on 2026-10-09 07:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0027_insightflag_detail_insightflag_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('sponsor_name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('alert_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sponsor_funds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('mobile_money', 'Mobile money')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_contributions', to='smmsapp.journalentry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_fund_contributions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='smmsapp.sponsorfund')),
            ],
        ),
        migrations.AddField(
            model_name='journalline',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='smmsapp.sponsorfund'),
        ),
        migrations.CreateModel(
            name='SponsorshipAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_types', models.JSONField(default=list)),
                ('daily_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_meal_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='smmsapp.sponsorfund')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('wallet', 'Wallet'), ('fund', 'Fund'), ('preorder', 'Pre-order')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='smmsapp.sponsorfund')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_payments', to='smmsapp.journalentry')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_parts', to='smmsapp.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sponsorshipallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('fund', 'student'), name='uniq_active_fund_student_allocation'),
        ),
        migrations.AddConstraint(
            model_name='transactionpayment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('fund__isnull', False), ('source', 'fund')), models.Q(models.Q(('source', 'fund'), _negated=True), ('fund__isnull', True)), _connector='OR'), name='txn_payment_fund_source_matches'),
        ),
    ]
