# Generated by Django 5.2.18 on 2026-10-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0029_seed_sponsor_fund_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNumberCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yymm', models.CharField(max_length=4)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_number_counters', to='smmsapp.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'yymm'), name='uniq_control_counter_school_month')],
            },
        ),
    ]
