# Generated by Django 5.2.18 on 2026-10-09 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0030_controlnumbercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='control_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.rfidcard', to_field='control_number'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='rfid_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.rfidcard'),
        ),
        migrations.AlterField(
            model_name='replacementlink',
            name='new_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_of', to='smmsapp.rfidcard'),
        ),
        migrations.AlterField(
            model_name='replacementlink',
            name='old_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='smmsapp.rfidcard'),
        ),
        migrations.AlterField(
            model_name='reversal',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.transaction'),
        ),
        migrations.AlterField(
            model_name='rfidcard',
            name='student_or_staff',
            field=models.ForeignKey(help_text='Owner of the card. A student/staff may have multiple cards', limit_choices_to={'role__in': ['student', 'staff']}, on_delete=django.db.models.deletion.PROTECT, related_name='rfid_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanneddata',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smmsapp.canteenitem'),
        ),
        migrations.AlterField(
            model_name='scanneddata',
            name='rfid_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.rfidcard'),
        ),
        migrations.AlterField(
            model_name='scanneddata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.scansession'),
        ),
        migrations.AlterField(
            model_name='scanneddata',
            name='student_or_staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['student', 'staff']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.canteenitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rfid_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smmsapp.rfidcard'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student_or_staff',
            field=models.ForeignKey(limit_choices_to={'role__in': ['student', 'staff']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
