# Generated by Django 5.2.18 on 2026-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmsapp', '0033_integrationclass_integrationkey_integrationsynclog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('deactivate', 'Deactivate'), ('activate', 'Activate'), ('delete', 'Delete'), ('approve', 'Approve'), ('reverse', 'Reverse'), ('replace', 'Replace'), ('login', 'Login'), ('integration_sync', 'Integration Sync')], max_length=20),
        ),
    ]
